remote_theme: mmistakes/minimal-mistakes@4.27.3
plugins:
- jekyll-remote-theme
- jekyll-include-cache
title: Dong Wenyi's Page!!
minimal_mistakes_skin: "dirt"
locale: "en-US"
logo: "/assets/images/logo.png"
include: ["_page","_includes"]

author: 
  name: "Dong Wenyi"
  avatar: "/assets/images/selfie.png"
  location : Beijing, China
  bio : "Everything is disgusting, but art and science are everlasting."

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

footer:
  custom_html:
  links: