remote_theme: mmistakes/minimal-mistakes@4.27.3
plugins:
- jekyll-remote-theme
- jekyll-include-cache
title: Dong Wenyi's Page!!
minimal_mistakes_skin: "air"
locale: "en-US"
logo: "/assets/images/logo.png"