remote_theme: mmistakes/minimal-mistakes@4.27.3
plugins:
- jekyll-remote-theme
- jekyll-include-cache
title: Dong Wenyi's Page!!
description: aka 'dot' and 'uruz'
header_pages:
  - Artworks.md
  - Researchs.md